name: CI

on: [push, pull_request]

jobs:
  rv32emu:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: install-dependencies
      run: | 
            sudo apt-get install build-essential device-tree-compiler
            sudo apt-get install expect
    - name: default build
      run: make ENABLE_SDL=0
      shell: bash
    - name: automated test
      run: .ci/autorun.sh
      shell: bash

  coding_style:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: coding convention
      run: |
            sudo apt-get install -q -y clang-format-12
            .ci/check-format.sh
      shell: bash
