name: CI

on: [push, pull_request]

jobs:
  semu-linux:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: install-dependencies
      run: |
            sudo apt-get install build-essential device-tree-compiler expect
            sudo apt-get install libasound2-dev libudev-dev
    - name: default build
      run: make
      shell: bash
    - name: automated test
      run: .ci/autorun.sh
      shell: bash
    - name: netdev test
      run: .ci/test-netdev.sh
      shell: bash
      if: ${{ success() }}

  semu-macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: install-dependencies
      run: |
            brew install make dtc expect e2fsprogs
    - name: default build
      run: make ENABLE_SDL=0
      shell: bash
    - name: automated test
      run: .ci/autorun.sh
      shell: bash

  coding_style:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: coding convention
      run: |
            sudo apt-get install -q -y clang-format-18
            .ci/check-format.sh
      shell: bash
